version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: chatbot_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        depends_on:
            - mysql
            - qdrant

    nginx:
        image: nginx:alpine
        container_name: chatbot_nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8
        container_name: chatbot_mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_DATABASE: chatbot_mysql_docker
            MYSQL_USER: chatbot_user
            MYSQL_PASSWORD: chatbot_pass
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    qdrant:
        image: qdrant/qdrant
        container_name: chatbot_qdrant
        ports:
            - "6333:6333"
            - "6334:6334" # gRPC (optional)

volumes:
    mysql_data:
